# Generated by Django 5.2.7 on 2025-10-11 00:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('EMPLEADO', 'Empleado'), ('CLIENTE', 'Cliente'), ('TRANSPORTISTA', 'Transportista'), ('CONSULTOR', 'Consultor')], default='CLIENTE', max_length=20, verbose_name='Rol del usuario')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
