# Generated by Django 5.2.7 on 2025-11-02 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('marca', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='perfil',
            name='rol',
            field=models.CharField(choices=[('ADMINISTRADOR', 'administrador'), ('productor', 'productor'), ('cliente', 'cliente'), ('TRANSPORTISTA', 'Transportista'), ('CONSULTOR', 'Consultor')], default='cliente', max_length=20, verbose_name='Rol del usuario'),
        ),
    ]
