# Generated by Django 5.2.7 on 2025-11-09 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_remove_orderitem_order_remove_orderitem_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='rol',
            field=models.CharField(choices=[('Administrador', 'administrador'), ('productor', 'productor'), ('cliente', 'cliente'), ('TRANSPORTISTA', 'Transportista'), ('CONSULTOR', 'Consultor')], default='cliente', max_length=20, verbose_name='Rol del usuario'),
        ),
    ]
