# Generated by Django 5.2.7 on 2025-11-09 02:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0006_contrato'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contrato',
            old_name='fecha',
            new_name='fecha_inicio',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='precio',
        ),
        migrations.AddField(
            model_name='contrato',
            name='fecha_termino',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='nombre_transporte',
            field=models.CharField(max_length=100),
        ),
    ]
