# Generated by Django 5.2.7 on 2025-11-29 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0007_rename_fecha_contrato_fecha_inicio_and_more'),
        ('aplicacion', '0008_auto_20251129_1907'),
    ]

    operations = [
    ]
