# Generated by Django 5.2.7 on 2025-11-30 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0009_merge_20251129_1917'),
    ]

    operations = [
        
       
        
    ]
