# Generated by Django 5.2.7 on 2025-11-30 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0010_fruta_imagen_pedido_direccion_envio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fruta',
            options={'ordering': ['nombre']},
        ),
        migrations.AddField(
            model_name='fruta',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='frutas/'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='direccion_envio',
            field=models.CharField(default='Dirección pendiente de registro', max_length=500, verbose_name='Dirección de Envío'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Bodega', 'En Bodega'), ('En Transporte', 'En Transporte'), ('Completado', 'Completado')], default='Pendiente', max_length=20, verbose_name='Estado del Pedido'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tipo_envio',
            field=models.CharField(choices=[('Nacional', 'Nacional'), ('Internacional', 'Internacional')], default='Nacional', max_length=15, verbose_name='Tipo de Envío'),
        ),
    ]
