# Generated by Django 5.2.7 on 2025-11-30 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0010_fruta_imagen_pedido_direccion_envio_and_more'),
    ]

    
