# Generated by Django 5.2.7 on 2025-11-30 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0010_fruta_imagen_pedido_direccion_envio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruta',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='frutas/'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='direccion_envio',
            field=models.CharField(default='Direccion temporal sin especificar', max_length=500, verbose_name='Dirección de Envío'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='tipo_envio',
            field=models.CharField(choices=[('Nacional', 'Nacional'), ('Internacional', 'Internacional')], default='Nacional', max_length=15, verbose_name='Tipo de Envío'),
        ),
    ]
