# Generated by Django 5.2.7 on 2025-12-01 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0011_alter_fruta_options_fruta_imagen_and_more'),
    ]

    
    
