# Generated by Django 5.2.7 on 2025-12-01 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0011_fruta_imagen_pedido_direccion_envio_and_more'),
        ('aplicacion', '0012_alter_fruta_options_fruta_imagen_and_more'),
    ]

    operations = [
    ]
