# Generated by Django 5.2.7 on 2025-12-01 22:43

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0015_fix_cloudinary_imagen'),
    ]

  