# Generated by Django 5.2.7 on 2025-12-05 00:12

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0018_alter_fruta_options_fruta_imagen_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]


