# Generated by Django 5.2.7 on 2025-12-05 01:30

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings
class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0019_alter_fruta_options_fruta_imagen_and_more'),
    ]

   
