# Generated by Django 5.2.7 on 2025-12-05 02:57

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0021_fruta_imagen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    
