# Generated by Django 5.2.7 on 2025-12-06 03:28

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0023_alter_fruta_options_fruta_imagen_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fruta',
            options={'ordering': ['nombre']},
        ),
        migrations.AddField(
            model_name='fruta',
            name='imagen',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='direccion_envio',
            field=models.CharField(default='Dirección pendiente de registro', max_length=500, verbose_name='Dirección de Envío'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Bodega', 'En Bodega'), ('En Transporte', 'En Transporte'), ('Completado', 'Completado')], default='Pendiente', max_length=20, verbose_name='Estado del Pedido'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tipo_envio',
            field=models.CharField(choices=[('Nacional', 'Nacional'), ('Internacional', 'Internacional')], default='Nacional', max_length=15, verbose_name='Tipo de Envío'),
        ),
        
        
        migrations.CreateModel(
            name='PedidosRealizados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('total_pedido', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('direccion_envio', models.CharField(default='Dirección pendiente de registro', max_length=500, verbose_name='Dirección de Envío')),
                ('tipo_envio', models.CharField(choices=[('Nacional', 'Nacional'), ('Internacional', 'Internacional')], default='Nacional', max_length=15, verbose_name='Tipo de Envío')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Bodega', 'En Bodega'), ('En Transporte', 'En Transporte'), ('Completado', 'Completado')], default='Pendiente', max_length=20, verbose_name='Estado del Pedido')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='aplicacion.pedidosrealizados'),
        ),
    ]
